sudo apt install figlet 
sudo apt install toilet
sudo apt install cowsay
sudo apt install sl
sudo apt install fortune
sudo apt install xcowsay
sudo apt install cmatrix
sudo apt install oneko
sudo apt install espeak
sudo apt install libaa-bin
sudo apt install linux_log
sudo apt install neofetch
sudo apt install sysvbanner
sudo apt install lolcat
